//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block_Mast
    {
        public int IDpk { get; set; }
        public int ID { get; set; }
        public Nullable<int> DistId_fk { get; set; }
        public string LG_Block_Code { get; set; }
        public string BlockName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
