//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UM_DBEntities : DbContext
    {
        public UM_DBEntities()
            : base("name=UM_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<Block_Mast> Block_Mast { get; set; }
        public virtual DbSet<Cluster_Mast> Cluster_Mast { get; set; }
        public virtual DbSet<Dist_Mast> Dist_Mast { get; set; }
        public virtual DbSet<State_Mast> State_Mast { get; set; }
        public virtual DbSet<tbl_LoginDetail> tbl_LoginDetail { get; set; }
        public virtual DbSet<tbl_Registration> tbl_Registration { get; set; }
        public virtual DbSet<tbl_CoursesDetail> tbl_CoursesDetail { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_Resource> tbl_Resource { get; set; }

        public System.Data.Entity.DbSet<UmangMicro.Models.ResourceModel> ResourceModels { get; set; }
    }
}
