//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UM_DBEntities : DbContext
    {
        public UM_DBEntities()
            : base("name=UM_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<Block_Mast> Block_Mast { get; set; }
        public virtual DbSet<Cluster_Mast> Cluster_Mast { get; set; }
        public virtual DbSet<Dist_Mast> Dist_Mast { get; set; }
        public virtual DbSet<State_Mast> State_Mast { get; set; }
        public virtual DbSet<tbl_LoginDetail> tbl_LoginDetail { get; set; }
        public virtual DbSet<tbl_CoursesDetail> tbl_CoursesDetail { get; set; }
        public virtual DbSet<tbl_Resource> tbl_Resource { get; set; }
        public virtual DbSet<tbl_MicroCase> tbl_MicroCase { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_Registration> tbl_Registration { get; set; }
        public virtual DbSet<Month_Master> Month_Master { get; set; }
        public virtual DbSet<Year_Master> Year_Master { get; set; }
        public virtual DbSet<QuestionRIASEC> QuestionRIASECs { get; set; }
        public virtual DbSet<RIASEC_Guided> RIASEC_Guided { get; set; }
        public virtual DbSet<tbl_CH_Scheme> tbl_CH_Scheme { get; set; }
        public virtual DbSet<tbl_CH_Scholarship> tbl_CH_Scholarship { get; set; }
        public virtual DbSet<tbl_CH_SkillT> tbl_CH_SkillT { get; set; }
        public virtual DbSet<tbl_CH_CourseD> tbl_CH_CourseD { get; set; }
        public virtual DbSet<tbl_CH_Psychometric> tbl_CH_Psychometric { get; set; }
        public virtual DbSet<SchoolMaster_N> SchoolMaster_N { get; set; }
        public virtual DbSet<BlockMaster_N> BlockMaster_N { get; set; }
        public virtual DbSet<DistrictMaster_N> DistrictMaster_N { get; set; }
        public virtual DbSet<tbl_RIASECTest> tbl_RIASECTest { get; set; }
        public virtual DbSet<tbl_RIASEC_Main> tbl_RIASEC_Main { get; set; }
        public virtual DbSet<tbl_CaseHistory> tbl_CaseHistory { get; set; }
        public virtual DbSet<ModularSessionMaster> ModularSessionMasters { get; set; }
        public virtual DbSet<tbl_Modular> tbl_Modular { get; set; }
        public virtual DbSet<DocumentType_Master> DocumentType_Master { get; set; }
        public virtual DbSet<Tbl_FileResource> Tbl_FileResource { get; set; }
        public virtual DbSet<Class_Master> Class_Master { get; set; }
        public virtual DbSet<tbl_Plan> tbl_Plan { get; set; }
        public virtual DbSet<Career_Master> Career_Master { get; set; }
        public virtual DbSet<Course_Master> Course_Master { get; set; }
        public virtual DbSet<Tbl_Training> Tbl_Training { get; set; }
        public virtual DbSet<Tbl_Trainingteacher> Tbl_Trainingteacher { get; set; }
    }
}
