//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dist_Mast
    {
        public int ID { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Dist_Code { get; set; }
        public string DistName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
