//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictMaster_N
    {
        public int ID { get; set; }
        public string DisCode { get; set; }
        public string DistNameEng { get; set; }
        public string DistNameHin { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
