//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModularSessionMaster
    {
        public int ID { get; set; }
        public string Session { get; set; }
        public string COHORT_Session_Hindi { get; set; }
        public string COHORT_Session_Eng { get; set; }
        public string TypeOfCohort { get; set; }
        public Nullable<int> Cohort { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
