//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionRIASEC
    {
        public int ID { get; set; }
        public string QuestionCode { get; set; }
        public string QuestionHindi { get; set; }
        public string Section { get; set; }
        public string ControlType { get; set; }
        public string Ques_Order { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
