//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIASEC_Guided
    {
        public int ID { get; set; }
        public string SectionShortEng { get; set; }
        public string SectionNameEng { get; set; }
        public string TypeofSectionEng { get; set; }
        public string SectionDetailNoEng { get; set; }
        public string SectionDetailEng { get; set; }
        public string SectionShortHindi { get; set; }
        public string SectionNameHindi { get; set; }
        public string TypeofSectionHindi { get; set; }
        public string SectionDetailNoHindi { get; set; }
        public string SectionDetailHindi { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
