//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMaster_N
    {
        public int ID { get; set; }
        public string udise_sch_code { get; set; }
        public string district_name { get; set; }
        public string block_name { get; set; }
        public string school_name { get; set; }
        public string TypeofSchool { get; set; }
        public string DistrictCode { get; set; }
        public string BlockCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
