//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CaseHistory
    {
        public Nullable<System.Guid> GudID { get; set; }
        public int Id { get; set; }
        public Nullable<int> Reg_Id_fk { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> RIASECTest_Id_fk { get; set; }
        public string CaseID { get; set; }
        public string FormSubmitTime { get; set; }
        public Nullable<System.DateTime> StratTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string TypeCounsellor { get; set; }
        public string TypeQuery { get; set; }
        public string KeyWords { get; set; }
        public string Study10th { get; set; }
        public string Study12th { get; set; }
        public string Subject { get; set; }
        public string Counselling { get; set; }
        public string IsPsychometric { get; set; }
        public string Psychometric { get; set; }
        public string Recommendation { get; set; }
        public string AreasImprovement { get; set; }
        public string IsFollow { get; set; }
        public string FM { get; set; }
        public string FY { get; set; }
        public string IsGoalClear { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CaseDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
