//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FileResource
    {
        public int FileId_pk { get; set; }
        public string FileGuid { get; set; }
        public string DocumentType { get; set; }
        public string LetterNo { get; set; }
        public string FileName { get; set; }
        public string FileImage { get; set; }
        public string AttachmentFile { get; set; }
        public string AttachmentImage { get; set; }
        public Nullable<System.DateTime> DateofIssue { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Upload_date { get; set; }
        public string UplaodBy { get; set; }
    }
}
