//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Registration
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string CaseID { get; set; }
        public string Name { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public string Sex { get; set; }
        public string Cast { get; set; }
        public string SchoolId { get; set; }
        public string StateId { get; set; }
        public string DistrictId { get; set; }
        public string BlockId { get; set; }
        public string PanchayatId { get; set; }
        public string VillageId { get; set; }
        public string VillageOther { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Age { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBY { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; set; }
    }
}
