//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CoursesDetail
    {
        public int ID { get; set; }
        public string NameCourseEng { get; set; }
        public string NameCourseHindi { get; set; }
        public string CourseTypeEng { get; set; }
        public string CourseTypeHindi { get; set; }
        public string JobOpportunityEng { get; set; }
        public string JobOpportunityHindi { get; set; }
        public string CourseDurationEng { get; set; }
        public string CourseDurationHindi { get; set; }
        public string ShortDescriptionCourseEng { get; set; }
        public string ShortDescriptionCourseHindi { get; set; }
        public string EligibilityEng { get; set; }
        public string EligibilityHindi { get; set; }
        public string MarksCriteriaEng { get; set; }
        public string MarksCriteriaHindi { get; set; }
        public string AdmissionProcessEng { get; set; }
        public string AdmissionProcessHindi { get; set; }
        public string MediumInstructionEng { get; set; }
        public string MediumInstructionHindi { get; set; }
        public string HostelAvailabilityEng { get; set; }
        public string HostelAvailabilityHindi { get; set; }
        public string AvailableScholarshipEng { get; set; }
        public string AvailableScholarshipHindi { get; set; }
        public string CategoryEng { get; set; }
        public string CategoryHindi { get; set; }
        public string CategoryOtherEng { get; set; }
        public string CategoryOtherHindi { get; set; }
        public string College_Unvty_InstEng { get; set; }
        public string College_Unvty_InstHindi { get; set; }
        public string FeeStructureEng { get; set; }
        public string FeeStructureHindi { get; set; }
        public string StatusInstitutionEng { get; set; }
        public string StatusInstitutionHindi { get; set; }
        public string DistrictEng { get; set; }
        public string DistrictHindi { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    }
}
