//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Registration
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string CaseID { get; set; }
        public string Name { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> ClusterId { get; set; }
        public string Village { get; set; }
        public string Visited { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Age { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> IsSkillTraining { get; set; }
        public Nullable<int> IsMarriage { get; set; }
        public Nullable<int> IsStudy { get; set; }
        public string SocialClass { get; set; }
        public string TillStudied { get; set; }
        public Nullable<int> IsWork { get; set; }
        public string Reason { get; set; }
        public Nullable<int> IsPsychometric { get; set; }
        public string PsyYes_Result { get; set; }
        public string Advice { get; set; }
        public Nullable<int> IsFollowUp { get; set; }
        public string FollowUp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBY { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDt { get; set; }
    }
}
