//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resource
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Designation_Other { get; set; }
        public string Organisation { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string Age { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string ResourceDownLoad { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
