//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Plan
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ConductedDate { get; set; }
        public Nullable<int> Reg_fk_Id { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> CalssId { get; set; }
        public string CalssMlt { get; set; }
        public Nullable<int> Task { get; set; }
        public Nullable<int> SessionType { get; set; }
        public Nullable<int> Session { get; set; }
        public Nullable<int> NoofStudent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        public string SessionInput { get; set; }
        public Nullable<System.DateTime> AchievementDate { get; set; }
        public Nullable<int> AchievedNoofStudent { get; set; }
        public string AchieveImagepath { get; set; }
    }
}
