//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmangMicro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Training
    {
        public int Id { get; set; }
        public Nullable<int> Trainingtype { get; set; }
        public Nullable<int> Round { get; set; }
        public string Nameofteacher { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Noofteachertrained { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        public string Session { get; set; }
        public string Comment { get; set; }
    }
}
